### ISSUE TITLE
Multiple Segmentation results

### ISSUE THREAD

**Issue by RoderickJDunn** [eskriett/spell#4]
Hi, great work on this library! It truly is very fast, and I like that you can save the dictionary as a binary.

I was wondering if there is a way to get multiple results from the Segment() function, rather than just the BestMatch? Even if this would involve modifying the library source, I'd be interested to know how I might go about this. 

Thanks!

**Comment by eskriett** [comment]
Hey thanks for the feedback. 

As you note this would require a large internal change to the segmentation function. Changing it to support multiple segmentation results isn't possible as the implementation has been designed to identify the 'best' segmentation variant for a specific substring to achieve the performance it does.

If you're interested in how the segmentation function operates, I would highly recommend reading [this post](https://towardsdatascience.com/fast-word-segmentation-for-noisy-text-2c2c41f9e8da) by Wolf Garbe the author of the original SymSpell library which provides details on the design choices made and comparison to other segmentation approaches.

While adding support for multiple segmentation isn't something I intend to add to the library, if you do need to segment a string into multiple variants than there are numerous approaches you could take in the program you're developing, including:

* A recursive approach. As mentioned in the post linked above, generate every possible substring of the input and run the [`Lookup()`](https://godoc.org/github.com/eskriett/spell#Spell.Lookup) function on each of the substrings. Keep specific collection of substrings based on some criteria. For example keep substrings where the combined edit distance of each substring suggestion is less than some threshold.

* Depending on what you're trying to achieve, you could run the [`Segment()`](https://godoc.org/github.com/eskriett/spell#Spell.Segment) function multiple times with varying [`DistanceFunc`](https://godoc.org/github.com/eskriett/spell#DistanceFunc) which prioritise certain word combinations over others.

Hope that helps,
Hayden
